class AppAppearance:
    """
    A python class containing all of the colors for the application, all in a place where they
    can be easily tweaked and changed.
    """

    WEBSITE_URL = "TBD"
    APP_NAME = "DataFlippers"

    MDI_AREA_COLOR = "#FFFFFF"
    TRAIN_BUTTON_BACKGROUND_COLOR =  "#FFFFFF"
    TRAIN_BUTTON_BACKGROUND_COLOR_HOVER = "#E3E3E3"


    MODEL_CORNER_RADIUS = 30

    BASE_PIPELINE_WIDTH = 400
    BASE_PIPELINE_HEIGHT = 400

    PIPELINE_TITLE_COLOR = "#040404"
    PIPELINE_HOVER_COLOR = "#F0F0F0"
    PIPELINE_BACKGROUND_COLOR = "#EDEDED"
    PIPELINE_NOT_HOVER_COLOR = "#FFFFFF"
    PIPELINE_HOLDER_BORDER_COLOR = PIPELINE_BACKGROUND_COLOR
    PIPELINE_PREPROCESSOR_BACKGROUND_COLOR = PIPELINE_BACKGROUND_COLOR

    DRAGGABLE_HOVER_COLOR = "#FFFFFF"
    DRAGGABLE_HOVER_BORDER_THICKNESS=3


    # Draggable Columns
    DRAGGABLE_COLUMN_COLOR = "#0C1990"
    DRAGGABLE_COLUMN_COLOR_CLASS = "#360C90"
    DRAGGABLE_COLOMN_BORDER_COLOR = "#040404"

    # REGRESSORS
    REGRESSOR_LINEAR_COLOR = "#ffa600"
    REGRESSOR_SUPPORT_VECTOR_MACHINES_COLOR = "#fa940f"
    REGRESSOR_ENSEMBLE_COLOR = "#f5821e"
    REGRESSOR_TREE_COLOR = "#f0702d"
    REGRESSORS_NEIGHBORS_COLOR = "#eb5d3c"
    REGRESSOR_NEURAL_COLOR = "#e44a4a"

    # CLASSIFIERS
    CLASSIFIER_LINEAR_COLOR = "#476eae"
    CLASSIFIER_SUPPORT_VECTOR_MACHINES_COLOR = "#3b6e93"
    CLASSIFIER_ENSEMBLE_COLOR = "#306e77"
    CLASSIFIER_TREE_COLOR = "#246e5c"
    CLASSIFIERS_NEIGHBORS_COLOR = "#186e41"
    CLASSIFIER_NEURAL_COLOR = "#0c6d25"


    # PRE_PROCESSORS
    PREPROCESSORS_SCALAR_COLOR = "#d488f6"
    PREPROCESSORS_CLUSTER_COLOR = "#d167f8"
    PREPROCESSORS_TRANSFORMER_COLOR = "#ad07f9"
    
    # VALIDATORS
    VALIDATOR_COLOR = "#068D41"
