

class AppAppearance():
	"""
	A python class containing all of the colors for the application, all in a place where they 
	can be easily tweaked and changed. 
	"""

	MDI_AREA_COLOR = "#252525"
	TRAIN_BUTTON_BACKGROUND_COLOR = "#4B4B4B"
	TRAIN_BUTTON_BACKGROUND_COLOR_HOVER = "#444444"

	MODEL_CORNER_RADIUS = 30

	BASE_PIPELINE_WIDTH = 400
	BASE_PIPELINE_HEIGHT = 400

	PIPELINE_TITLE_COLOR = "#FFFFFF" 
	PIPELINE_HOVER_COLOR = "#5D5C5C"
	PIPELINE_BACKGROUND_COLOR = "#1F1F1F"
	PIPELINE_NOT_HOVER_COLOR = "#353535"
	PIPELINE_HOLDER_BORDER_COLOR = PIPELINE_BACKGROUND_COLOR
	PIPELINE_PREPROCESSOR_BACKGROUND_COLOR = PIPELINE_BACKGROUND_COLOR

	DRAGGABLE_HOVER_COLOR = "#a9a9a9"

	# Draggable Columns
	DRAGGABLE_COLUMN_COLOR = "#0C1990"
	DRAGGABLE_COLOMN_BORDER_COLOR = "#040404"
	
	# REGRESSORS
	REGRESSOR_LINEAR_COLOR = "#ffa600" 
	REGRESSOR_ENSEMBLE_COLOR = "#ff8531"
	REGRESSOR_TREE_COLOR = "#ff6361"
	REGRESSOR_NEURAL_COLOR = "#de5a79"

	# CLASSIFIERS
	CLASSIFIER_LINEAR_COLOR = "#476EAE"
	CLASSIFIER_ENSEMBLE_COLOR = "#48B3AF"
	CLASSIFIER_TREE_COLOR = "#72DD59"
	CLASSIFIER_NEURAL_COLOR = "#02A376"

	# PRE_PROCESSORS
	PREPROCESSOR_COLOR = "#5D0F91"
	PREPROCESSOR_BORDER_COLOR = "#5D0F9D"

	# VALIDATORS
	VALIDATOR_COLOR = "#068D41"

	