class AppAppearance:
    """
    A python class containing all of the colors for the application, all in a place where they
    can be easily tweaked and changed.
    """

    WEBSITE_URL = "TBD"
    APP_NAME = "DataFlippers"

    MDI_AREA_COLOR = "#FFFFFF"
    TRAIN_BUTTON_BACKGROUND_COLOR =  "#E0E0E0"
    TRAIN_BUTTON_BACKGROUND_COLOR_HOVER = "#E3E3E3"


    MODEL_CORNER_RADIUS = 30

    BASE_PIPELINE_WIDTH = 400
    BASE_PIPELINE_HEIGHT = 400

    PIPELINE_TITLE_COLOR = "#040404"
    PIPELINE_HOVER_COLOR = "#F0F0F0"
    PIPELINE_BACKGROUND_COLOR = "#EDEDED"
    PIPELINE_NOT_HOVER_COLOR = "#FFFFFF"
    PIPELINE_HOLDER_BORDER_COLOR = PIPELINE_BACKGROUND_COLOR
    PIPELINE_PREPROCESSOR_BACKGROUND_COLOR = PIPELINE_BACKGROUND_COLOR

    DRAGGABLE_HOVER_COLOR = "#000000"
    DRAGGABLE_HOVER_BORDER_THICKNESS=5


    # Draggable Columns
    DRAGGABLE_COLUMN_COLOR = "#0C1990"
    DRAGGABLE_COLUMN_COLOR_CLASS = "#360C90"
    DRAGGABLE_COLOMN_BORDER_COLOR = "#040404"

    # REGRESSORS
    REGRESSOR_LINEAR_COLOR = "#ffa600"
    REGRESSOR_SUPPORT_VECTOR_MACHINES_COLOR = "#ff8531"
    REGRESSOR_ENSEMBLE_COLOR = "#ff6361"
    REGRESSOR_TREE_COLOR = "#de5a79"
    REGRESSOR_NEURAL_COLOR = "#de5a5a"

    # CLASSIFIERS
    CLASSIFIER_LINEAR_COLOR = "#476EAE"
    CLASSIFIER_SUPPORT_VECTOR_MACHINES_COLOR = "#48B3AF"
    CLASSIFIER_ENSEMBLE_COLOR = "#72DD59"
    CLASSIFIER_TREE_COLOR = "#02A376"
    CLASSIFIER_NEURAL_COLOR = "#02A32A"

    # PRE_PROCESSORS
    PREPROCESSOR_COLOR = "#5D0F91"
    PREPROCESSOR_BORDER_COLOR = "#5D0F9D"

    # VALIDATORS
    VALIDATOR_COLOR = "#068D41"
